### ISSUE TITLE
:reload doesn't seem to be working

### ISSUE THREAD

**Issue by vicvicvic** [pandeiro/boot-http#15]
I'm new to Clojure, so this might be an issue with me misunderstanding the purpose of the `:reload` when using `:handler`. My perception is that using it will automatically reload any changed namespaces on demand, so that I can just refresh a page in my browser and the updated code will be served. This doesn't seem to be working on my machine.

Minimal (non)-working example:

***build.boot***
```clojure
(set-env!
  :source-paths #{"src"}
  :dependencies '[[lib-noir "0.9.5"]
                  [pandeiro/boot-http "0.6.3-SNAPSHOT"]])

(require '[pandeiro.boot-http :refer [serve]])

(deftask develop
  "Run a development server"
  []
  (comp (serve :handler 'victorandree-se.handler/app
               :reload)
        (wait)))
```

***src/victorandree_se/handler.clj***
```clojure
(ns victorandree-se.handler
  (:require [compojure.core :refer [defroutes, GET]]
            [noir.util.middleware :refer [app-handler]]))

(defn home-page [] "Hello world, how are you?")

(defroutes my-routes
  (GET "/" [] (home-page)))

(def app (app-handler [my-routes]))
```

Changing the response from `home-page` and reloading my server does not result in any change for me. 

*Edit:* I'm using `lib-noir` here because I was getting started with Luminus ([well, guess I shouldn't][luminus]). But just a plain ol' ring handler has the same issue, replace `app` with e.g.

```clojure
(defn app [request]
  {:status 200 :body "Hello world"})
```

also doesn't reload.

[luminus]: http://yogthos.net/posts/2015-02-28-Luminus-2.0.html

**Comment by martinklepsch** [comment]
Did you try with a call to `serve` like so:

```cli
(serve :handler 'victorandree-se.handler/app
               :reload true)
```

The way arguments are passed to the `serve` function is a form of "keyword arguments" so I assume that if you don't supply a value to the `:reload` key it will be `nil` which has the same effect as setting it to false.

Hope that helps :smiley:

**Comment by vicvicvic** [comment]
:+1: :star: Can't believe I missed that!
