### ISSUE TITLE
Regression: if the -d folder doesn't exist yet, boot-http fails

### ISSUE THREAD

**Issue by mrcslws** [pandeiro/boot-http#16]
This worked in `0.3.0`, and the example code in <https://github.com/adzerk/boot-cljs-example> depends on it.

If you take that example, upgrade it to `0.6.3-SNAPSHOT`, and change it from `pandeiro.http` to `pandeiro.boot-http`, then run the recommended command
```
boot serve -d target/ watch speak reload cljs-repl cljs -sO none
```

it will fail because the `target` directory hasn't been generated yet. And this blocks the directory from getting created.

```
clojure.lang.ExceptionInfo: java.lang.Exception: Directory does not exist: target/
```

**Comment by pandeiro** [comment]
Hi @mrcslws, thanks for pointing this out. Closing as it should be fixed in 0.6.3-SNAPSHOT.
