### ISSUE TITLE
Exception: Could not locate pandeiro/http__init.class or pandeiro.http.clj

### ISSUE THREAD

**Issue by hura** [pandeiro/boot-http#17]
I keep getting the following error:
```bash
   clojure.lang.ExceptionInfo: Could not locate pandeiro/http__init.class or pandeiro/http.clj on classpath: 
    data: {:file "/tmp/boot.user1556625102114653636.clj", :line 11}
java.io.FileNotFoundException: Could not locate pandeiro/http__init.class or pandeiro/http.clj on classpath:
```

Fails with all >=0.4.2. Works with 0.4.0.

**Comment by martinklepsch** [comment]
I think the namespaces changed. Make sure your require calls are correct.

On Wednesday, March 18, 2015, hura <notifications@github.com> wrote:

> I keep getting the following error:
>
>    clojure.lang.ExceptionInfo: Could not locate pandeiro/http__init.class or pandeiro/http.clj on classpath:
>     data: {:file "/tmp/boot.user1556625102114653636.clj", :line 11}
> java.io.FileNotFoundException: Could not locate pandeiro/http__init.class or pandeiro/http.clj on classpath:
>
> Fails with all >=0.4.2. Works with 0.4.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pandeiro/boot-http/issues/17>.
>


-- 
—
Martin
http://martinklepsch.org <http://martinklepsch.org?ref=email>

**Comment by pandeiro** [comment]
Thanks @martinklepsch , @hura that is it indeed. The namespace you want it `pandeiro.boot-http` -- it was changed to follow the growing naming convention for boot-specific libraries.

**Comment by hura** [comment]
Thanks for the quick answer. Minor enhancement: When `:dir` does not exist, it just exists quietly without ever saying anything. Can be frustrating for beginners IMO.
