### ISSUE TITLE
Serving static files from other jars

### ISSUE THREAD

**Issue by piranha** [pandeiro/boot-http#4]
Would be nice to be able to include some dependency as a jar and then reference any JS file there in my `index.html` file.

**Comment by pandeiro** [comment]
@piranha Try doing this now with 0.4.0 -- it should serve stuff on the classpath do that an index.html somewhere can refer to eg 'reagent/react.min.js' (if you had reagent, for example)

**Comment by piranha** [comment]
Nice! It works. :)
