### ISSUE TITLE
What does watch do?

### ISSUE THREAD

**Issue by karneaud** [pandeiro/boot-http#50]
Forgive me for me ignorance but what does watch do in

```
(deftask dev []
  (comp (serve :dir "resources/public" :port 3000)
        (watch)
        (reload :port 9001)
        (cljs-repl :nrepl-opts {:port 9000})
        (cljs :ids #{"js/main"} :source-map true :optimizations :none)
        (target :dir #{"resources/public"})
        ))
```

does it watch for changes in cljs files? does it triggerr any recompile functions to js?

**Comment by sinistral** [comment]
The short answer to your question is: yes.

[`watch`](https://github.com/boot-clj/boot/blob/master/doc/boot.task.built-in.md#watch) is a built-in Boot task.  It watches for changes in the fileset and triggers the tasks that follow it when a change is detected.

**Comment by pandeiro** [comment]
Closing this as it's not specifically related to this package.
