### ISSUE TITLE
noob quickstart: nrepl not found

### ISSUE THREAD

**Issue by lsenta** [pandeiro/boot-http#57]
The basic example on the readme does not work, as the modern-cljs tutorial.
Both fail with error below.

I fixed it by adding `[org.clojure/tools.nrepl "0.2.12"]` to my dependencies.

```
› boot serve wait
             clojure.lang.ExceptionInfo: java.io.FileNotFoundException: Could not locate clojure/tools/nrepl/server__init.class or clojure/tools/nrepl/server.clj on classpath., compiling:(boot/repl_server.clj:1:1)
    data: {:file
           "/var/folders/6s/40bw5z1d66ncm83lfgwxjpv40000gn/T/boot.user3641210649331829851.clj",
           :line 11}
clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate clojure/tools/nrepl/server__init.class or clojure/tools/nrepl/server.clj on classpath., compiling:(boot/repl_server.clj:1:1)
          java.io.FileNotFoundException: Could not locate clojure/tools/nrepl/server__init.class or clojure/tools/nrepl/server.clj on classpath.
 ```

Does it mean that boot doesn't have dependency resolution? Or something missing in the doc?

**Comment by hellonico** [comment]
A required dependency is not being pulled in with the current boot-http when running from the command line.

You can simply try boot-http previous' version (0.7.5), by using the following command: 

```
boot -d pandeiro/boot-http:0.7.5 serve -d . wait 
```

or alternatively, you can add the dependency yourselv:

```
boot -d org.clojure/tools.nrepl -d pandeiro/boot-http serve -d . wait
```

**Comment by bhagany** [comment]
This is fixed here, awaiting a merge: https://github.com/pandeiro/boot-http/pull/61

**Comment by pandeiro** [comment]
This is now fixed as of `0.8.1`.

**Comment by lsenta** [comment]
Thanks for the fix!

**Comment by phi1ipp** [comment]
bumping boot-http up to 0.8.1 fixed the issue for me as well
